# Generated by Django 6.0.4 on 2026-05-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_alter_constituency_id_alter_district_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='party',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='representative',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
