# Generated by Django 6.0.4 on 2026-05-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_constituency_party_constituency_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_upcoming', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
